### ISSUE TITLE
Some packages not found with epel repo config from this cookbook

### ISSUE THREAD

**Issue by daften** [sous-chefs/yum-epel#48]
### Cookbook version
2.1.2

### Chef-client version
13.4.24

### Platform Details
Centos 7.4, vagrant box bento/centos-7.4

### Scenario:
I need to install libargon2 package

### Steps to Reproduce:
Set up an empty vagrant box with bento/centos-7.4 and use the yum-epel::default recipe. Vagrantfile we use for this can be found here: https://gist.github.com/daften/088d7bd55f97a24994ac545eaec7ed1e
Afterwards, perform a yum update and yum search libargon2

### Expected Result:
To see two packages: libargon2 and libargon2-devel in the list.

### Actual Result:
No results are shown. If I install epel through the rpm package (yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm), the packages are found. The two configs for epel.repo:

epel.repo from yum-epel:
```
# This file was generated by Chef
# Do NOT modify this file by hand.

[epel]
name=Extra Packages for 7 - $basearch
enabled=1
failovermethod=priority
fastestmirror_enabled=0
gpgcheck=1
gpgkey=https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch
```

epel.repo from the rpm package:
```
[epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
...
```

If I add the metalink line from the rpm package repo config to the config generated by this cookbook, the packages are found. My knowledge of yum repositories is not big enough atm to find out what causes this. Any input is welcome.

**Comment by filltr** [comment]
When this will be fixed. All tests using this cookbook failing because of this. Please fix it.
