### ISSUE TITLE
4.x released drops support for Oracle EL

### ISSUE THREAD

**Issue by wdeviers** [sous-chefs/yum-epel#65]
## :ghost: Brief Description

yum-epel 4.x fails on Oracle Enterprise Linux

## :pancakes: Cookbook version

4.0.0

## :woman_cook:  Chef-Infra Version

Cinc 15, Chef 14

## :tophat: Platform details

Oracle Platform (specifically 7.4)

## Steps To Reproduce

1. Have an Oracle EL host running < 4.0.0
2. Update environment pin

## :heavy_plus_sign: Additional context

We've been running yum-epel against OEL 7.4 images for a few years supporting Oracle DB intallations.  These are our only Oracle Linux installs so we don't really do much with them, but the epel sources work fine since it's really just RH7 rebranded. 

3.x had this stanza in attributed/default
`default['yum-epel']['repos'] = %w(
  epel
  epel-debuginfo
  epel-source
  epel-testing
  epel-testing-debuginfo
  epel-testing-source
)
`

Which basically works for everything - if you apply the recipe, it works.

4.x has, instead:

`  value_for_platform(
    %w(redhat centos) => {
....
    'amazon' => {
`

Chef defines OEL as:
`chef_version=15.14.0
platform=oracle
platform_version=7.4
`

It is probably sufficient just to add 'oracle' to the first platform set.

**Comment by ramereth** [comment]
Ah yes, sorry for missing that. We just got this cookbook imported into Sous Chefs so please give us a few days or a week to get it properly adopted so we can make this change.

**Comment by wdeviers** [comment]
No problem!  Thanks for jumping on it.

**Comment by ramereth** [comment]
@wdeviers can you please confirm my PR fixes the issue for you?
