### ISSUE TITLE
aarch64 not supported

### ISSUE THREAD

**Issue by sean-smith** [sous-chefs/yum-epel#69]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When the machine is `aarch64` yum-epel is not installed, i.e. on here's what the chef attributes look like:

```json
{
  "kernel": {
    "name": "Linux",
    "release": "4.18.0-193.28.1.el7.aarch64",
    "version": "#1 SMP Wed Oct 21 16:25:35 UTC 2020",
    "machine": "aarch64",
    "processor": "aarch64",
```

It looks like there was a PR to add arm 32 support https://github.com/sous-chefs/yum-epel/pull/53 but not aarch64. 

## :pancakes: Cookbook version

yum-epel 3.3.0

## :woman_cook:  Chef-Infra Version

Version of chef-client in your environment.

## :tophat: Platform details

Centos 7 - ARM 
c6g.2xlarge - AWS Graviton 2

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by ramereth** [comment]
AFAIK this should work, can you please provide some error logs so we can see what's happening specifically?

**Comment by ramereth** [comment]
I believe this should be working. Please re-open if this incorrect.
